C
C PURPOSE: ADMINISTERS CALLING FOR SYNTHESIS OF M1  LINES AT EACH VOXEL
C
C INPUTS: 
C
C OUTPUTS:
C
C COMMON:
C
C COMMENTS: OCTOBER 6, 1999, P. JUDGE
C
	SUBROUTINE DBTINYE
C
C  SUBROUTINE FOR GENERATION OF EMISSION COEFFICIENTS
C
	INCLUDE 'PREC'
	INCLUDE 'PARAM'
	INCLUDE 'CSE'
	INCLUDE 'CGRID'
	INCLUDE 'CATOM'
	INCLUDE 'CATMOS'
	INCLUDE 'CSLINE'
	INCLUDE 'CORON'
	INCLUDE 'CCONST'
	INCLUDE 'CINPUT'
	INCLUDE 'CINTS'
	INCLUDE 'CLU'
C
     	DIMENSION AA(MJTOT,MJTOT),BB(MJTOT)
     	DIMENSION T0(0:3,0:2)
	LOGICAL DISK,IGNORE
        DIMENSION SIGMA(MLINE)
C       
C	CALL CPTIME('DBE',0,0,2)
C
C  SKIP IF LOS INTERSECTS THE DISK
C
	DISK=.FALSE.
	RRR=GZ*GZ+GY*GY
	IF(RRR .LE. ONE) DISK= .TRUE.
	GX2=GX*GX
	GY2=GY*GY
	GZ2=GZ*GZ
C       
	ALPHA=-ATAN2(GX,SQRT(RRR))
C       
C       IGNORE THOSE LOCATIONS WHERE LINE OF SIGHT IS EITHER
C       1. ON THE DISK
C       2. HAS ELECTRON DENSITY BELOW SMALL N
C       3. HAS SMALL ION FRACTIONS 
C       
	IGNORE= DISK 
	IF(.NOT. IGNORE) THEN 
	   CALL PROFIL
C       
C       LTE POPULATIONS AND COLLISIONAL RATES TO BE STORED
C       
	   IF(ICOLL .NE. 0) THEN 
	      CALL LTEPOP
	      CALL COLCAL
	   ENDIF
C       
C       BUILD AND SOLVE STATISTICAL EQUILIBRIUM EQUATIONS
C       
	   CALL SE0_BUILD(NDIM)
	   CALL SOLVE(NDIM,AA,BB)
	   IF(IDEBUG.EQ.1) WRITE(LOUT,100) 'DBTINYE: TEMP, ED',TEMP,ED
 100	   FORMAT(A,1P,2(1X,E9.2))
	   CALL SE0_COPY(NDIM,BB)
C
	   DO KR=1,NLINE
	      IJ1=JRAD(KR)
	      SIGMA(KR)=RHO(IJ1,2)/RHO(IJ1,0)
	   END DO
           write(LDB) (SIGMA(KR),KR=1,NLINE)
	END IF
	RETURN
	END

