C
C PURPOSE: CALCULATES VARIATIONS OF LINES WITH ELECTRON DENSITY AT A GIVEN RADIUS
C
C INPUTS:
C       RAD    RADIUS OF POINT RELATIVE TO SUN CENTER, UNITS OF SOLAR RADII
C       THET   AZIMUTHAL ANGLE, UNITS RADIANS, IN S FRAME
C       PH     POLAR ANGLE, UNITS RADIANS, IN S FRAME
C       IPRINT SET TO 1 FOR MORE VERBOSE OUTPUT
C
C
C       ALSO READS FILE "SHEET.DAT" IN ORDER TO DEFINE WHAT KIND 
C       OF CALCULATION.  
C
C OUTPUTS:
C       B      MAGNITUDE OF FIELD
C       T      POLAR ANGLE
C       P      AZIMUTHAL ANGLE
C       EDENS  ELECTRON DENSITY /CM3
C       HDENS  HYDROGEN NUCLEI DENSITY /CM3 
C       TEMP   ELECTRON TEMPERATURE K
C       VEL    FLOW VELOCITY ALONG LINE OF SIGHT (+VE MEANS TOWARDS OBSERVER)
C       TURBV  MICROTURBULENCE KM/S (CONTRIBUTES TO LINE PROFILE WIDTHS)
C COMMON:
C
C COMMENTS: AUGUST 24, 2000, P. JUDGE
C
C NOTES:    USER-SUPPLIED ROUTINE
C 
	SUBROUTINE DVARY(RAD,THET,PH,B,T,P,EDENS,HDENS,
     *    TEMP,VEL,TURBV,IPRINT)
	INCLUDE 'PREC'
	PARAMETER(MCEN=10)
	DIMENSION YCEN(MCEN), ZCEN(MCEN), BCEN(MCEN)
	CHARACTER*(4) SKIND
        INCLUDE 'CCONST'
	INCLUDE 'CGRID'
	INCLUDE 'CINPUT'
	INCLUDE 'CLU'
	COMMON /WATM/BX,BY,BZ
	DATA ICALL, ZER, SMALL /0,0.,1.E-20/
C
C 
C  CALCULATE CARTESIAN COORDINATES OF THE POINT RAD,THET,PH
C       AND SET VALUES FAR FROM THE CURRENT SHEET
C	
	X=RAD*SIN(THET)*COS(PH)
	Y=RAD*SIN(THET)*SIN(PH)
	Z=RAD*COS(THET)
C
C       RANDOM MAGNETIC FIELD 
C
        B=10.
        T=PI*RAND()
        P=2.*PI*RAND()
        BX=B*COS(T)*SIN(P)
        BY=B*SIN(T)*SIN(P)
C        BY=B
        BZ=B*COS(T)
C
C     LOGARITHMIC INCREASE IN NE BETWEEN 1.1 AND 1.2 RADII
C
        R=(Y-1.1)*100.
        EDENS = 1.E6 * 10.**R
        temp=1.6e6
        vel=0.
        turbv=10.
        IF(ABS(Z) .GT. 0.03) THEN
	   EDENS=EDENS/1.e20
	ENDIF
        HDENS=0.8*EDENS
        RETURN
	END
